Add tests for github
pulumi/pulumi-github pull request #634
Opened 2024-04-08 18:08 UTC by VenelinMartinov

This PR adds tests for the following resources:

index_repositoryautolinkreference
index_repositorywebhook

2024-05-01 02:24 UTC, guineveresaenger requested changes
I'm not 💯 sure if our [test org](https://github.com/moolumi) token is correctly scoped for these two specific resources but getting those env vars set in the programtest file should be the way to go.

2024-05-01 02:24 UTC, guineveresaenger commented on provider/provider_program_test.go
> +		opttest.LocalProviderPath(providerName, filepath.Join(cwd, "..", "bin")),
You'll want to set `github:token` and `github:owner` to `GITHUB_TESTING_TOKEN` and `GITHUB_ORG`, respectively. Then CI should pass.

See how integration tests are set up: 
https://github.com/pulumi/pulumi-github/blob/master/examples/examples_test.go#L15

2024-06-07 18:25 UTC, guineveresaenger approved these changes

2024-06-07 18:25 UTC, guineveresaenger commented on provider/go.mod
> +require github.com/stretchr/testify v1.9.0
nit: can this be grouped with the other `require`s?

2024-06-07 18:34 UTC, VenelinMartinov commented
blocked on https://github.com/pulumi/pulumi-github/issues/636

2024-06-11 17:17 UTC, closed without merging